# Generated by Django 4.2.2 on 2023-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_anonymoususer_alter_note_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
