# Generated by Django 4.2.2 on 2023-07-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantite',
        ),
    ]
