# Generated by Django 4.2.2 on 2023-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tailleL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleXL',
            field=models.IntegerField(default=0),
        ),
    ]
