# Generated by Django 4.2.2 on 2023-07-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_taillel_alter_product_taillem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tailleL',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tailleM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tailleS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tailleXL',
        ),
    ]
