# Generated by Django 4.2.2 on 2023-07-08 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_product_note2_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='note2',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
